[project]
name = "f1llm"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ThallesNonato1123", email = "eusouthalles@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastf1>=3.8.3",
]

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
